[window]
dimensions = { columns = 100, lines = 30 }

[window.padding]
x = 10
y = 10

[font]
size = 12

[font.normal]
family = "BlexMonoNerdFontMono"
style = "Regular"

[font.bold]
family = "BlexMonoNerdFontMono"
style = "Bold"

[font.italic]
family = "BlexMonoNerdFontMono"
style = "Italic"

[font.bold_italic]
family = "BlexMonoNerdFontMono"
style = "Bold Italic"

[general]
import = [
    "~/.config/alacritty/themes/nordic.toml"
]

[selection]
save_to_clipboard = true

[cursor]
unfocused_hollow = true

[cursor.style]
shape = 'Beam'

[[keyboard.bindings]]
key = "Enter"
mods = "Alt"
action = "ToggleFullscreen"
