## family = "BlexMonoNerdFontMono"
[window]
dimensions = { columns = 100, lines = 30 }
decorations = "None"

[window.padding]
x = 10
y = 10

[font]
size = 12

[font.normal]
family = "InconsolataLGCNerdFont"
style = "Regular"

[font.bold]
family = "InconsolataLGCNerdFont"
style = "Bold"

[font.italic]
family = "InconsolataLGCNerdFont"
style = "Italic"

[font.bold_italic]
family = "InconsolataLGCNerdFont"
style = "Bold Italic"

[general]
import = [
    "~/.config/alacritty/themes/nordic.toml"
]
